ianbayne/counselor

app/models/appointment.rb, app/models/counsellor.rb, app/models/user.rb, db/migrate/20171024055126_create_appointments.rb, db/schema.rb
=> Create Appointment model, add has_many to counsellor and user models

app/controllers/appointments_controller.rb, app/controllers/counsellors_controller.rb, app/controllers/goals_controller.rb, app/controllers/reviews_controller.rb, app/controllers/users_controller.rb
@mdmss37, @MisterEnzo, @Tivo389 
Does this look good?
=> Make all controllers

app/models/goal.rb, app/models/mood.rb, app/models/review.rb, app/models/user_profile.rb, db/migrate/20171024062200_create_user_profiles.rb, db/migrate/20171024062314_create_goals.rb, db/migrate/20171024062401_create_reviews.rb, db/migrate/20171024062436_create_moods.rb
@mdmss37, @MisterEnzo, @Tivo389 
Here are the other models. Does this look right? Am I forgetting anything?
=> Make other models

Gemfile, Gemfile.lock, app/models/counsellor.rb, app/uploaders/photo_uploader.rb, app/views/counsellors/show.html.erb, db/seeds.rb
Add photobundler(cloudinary and carrierwave), update counsellor seed with photo.
Need bundle install after pull origin master.
=> Photobundler

app/controllers/messages_controller.rb, app/views/conversations/create.js.erb, app/views/conversations/new.html.erb, app/views/conversations/show.html.erb, app/views/messages/_form.html.erb, app/views/messages/_show.html.erb, app/views/messages/create.js.erb, config/application.rb
=> Make chat realtime

app/controllers/answers_controller.rb, app/controllers/users/registrations_controller.rb, app/views/answers/new.html.erb, app/views/users/registrations/new.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
answer/new -> Based on answer to question, send user to user/sign_up and filtered 3 counsellors are shown to user.
there are cases that 0 counsellor is available(user choose 4 speciality or check both male and female counsellor) which need to deal with.
=> Answer page

app/views/appointments/index.html.erb, db/seeds.rb
I also removed unnecessary lines in the index.html.erb
=> added 5 appointments to seed file

config/routes.rb
added route for appointments/show for users, so they can see the calendar of their counsellor
=> added users/:id/appointments/:id

app/controllers/appointments_controller.rb, app/controllers/users_controller.rb, app/views/appointments/index.html.erb, app/views/shared/_calendar.html.erb, config/routes.rb
A user just can make an appointment with a counsellor from user dashboard. No counsellor availability is considered.
=> Create new appointment from dashboard

app/controllers/counsellors/registrations_controller.rb, app/controllers/users/registrations_controller.rb
User and Counsellor will redirect to their dashboard after sign up. tested in local and it works.
=> go dashboard after sign up

app/controllers/pages_controller.rb, app/controllers/users/registrations_controller.rb
Without answering question, user will be redirect to home page.
=> user need to visit answer page before sign up page

app/controllers/users/registrations_controller.rb
added welcome message from the counsellor to initiate the conversation
=> Test message

app/views/answers/new.html.erb
Changed the outer label for question checkboxes.
=> question label update

db/seeds.rb
destroy appointment and question before seed
=> destroy question and appointment in seed

Gemfile, Gemfile.lock, app/assets/stylesheets/pages/_answer.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/answers_controller.rb, app/controllers/users/registrations_controller.rb, app/views/answers/new.html.erb, db/migrate/20171029032542_add_introduction_to_counsellor.rb, db/schema.rb, db/seeds.rb
1. Introduction text attribute(column) to counsellor
2. Counsellor seed with Japanese name and fixed text of introduction
3. radio box for gender preference of counsellor
4. active:false for gender question in db
=> Introduction attribute, seed update, radio box

app/views/users/registrations/new.html.erb
By clicking cousellor card, counsellor select form is updated with that counsellor.
=> Select counsellor

app/views/layouts/application.html.erb, app/views/shared/_mood_tracker.html.erb, db/seeds.rb
Mood chart added to dashboard, need support for styling....
=> Chart update

app/controllers/users_controller.rb, app/views/shared/_mood_tracker.html.erb
Add condition that user has mood/ no mood case for user/show(mood tracker)
=> protect no mood case

app/assets/stylesheets/components/_modal.scss, db/seeds.rb
1. update seed with real counsellor photo 
2. counsellor id 1 - 10 are male, 11 -20 are female
3. want to check if this seed can work in heroku as well
=> Seed update

app/views/users/registrations/new.html.erb, db/seeds.rb
Set custom introduction comment in seed for 3 counsellors who will be shown in the demo.
=> custom introduction for 3 counsellors

app/controllers/goals_controller.rb
In goal controller destroy, check goal exists or not to prevent error when double click delete goal button.
=> Check goal exists or not before destroy
